name: check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-14]
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@master
        with:
          name: cspr
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: System Info
        run: |
          uname -a
          nix --version

      - name: cctl-rs (x86_64-darwin)
        if: matrix.os == 'macos-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-darwin.cctld

      - name: cctl-rs (aarch64-darwin)
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.cctld
